name: Python Package using Conda

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
    - name: Look at CUDA version
      run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        nvcc -V

    - name: Checkout to current code
      uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: |
        scripts/install_third_party_dependencies.sh
    - name: Activate virtual environment
      run: |
        source scripts/activate_conda_env.sh
    - name: Compile OpenFold's CUDA kernel
      run: |
        python3 setup.py install
    - name: Deactivate virtual environment
      run: |
        source scripts/deactivate_conda_env.sh